const SUPABASE_URL='https://gbimzagwjcgblcecposy.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_XToT7s_XGQ2eXZtW3vh5eg_SiR21pQJ';
let skuData=demoSkuData.map(item=>({...item,history:[...(item.history||[])],curve:[...(item.curve||[])]}));
let eventData=[];
let databaseReady=false;
const pendingCsv={sales:null,products:null};

async function databaseRequest(path,options={}){
  const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:{apikey:SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json',...(options.headers||{})}});
  const body=await response.text();
  if(!response.ok)throw new Error(body||`HTTP ${response.status}`);
  return body?JSON.parse(body):null;
}
function status(message,offline=false){const el=document.getElementById('dbStatus');el.textContent=message;el.classList.toggle('error',offline)}
function messageFor(id,text,isError=false){const el=document.getElementById(id);el.textContent=text;el.classList.toggle('error',isError)}
function clone(value){return JSON.parse(JSON.stringify(value))}
function storeOptions(includeAll=false){return `${includeAll?'<option value="all">全店舗</option>':''}`+Object.entries(storeInfo).map(([id,store])=>`<option value="${id}">${escapeNo10Html(store.name)} · ${escapeNo10Html(store.area)}</option>`).join('')}
function refreshSelectors(){const select=document.getElementById('salesStore'),selected=select.value;select.innerHTML=storeOptions();if(selected&&storeInfo[selected])select.value=selected;document.getElementById('newStore').innerHTML=storeOptions();document.getElementById('eventStore').innerHTML=storeOptions(true);refreshSalesSkus();refreshEventSkus()}
function refreshSalesSkus(){const store=document.getElementById('salesStore').value,list=skuData.filter(item=>item.store===store);document.getElementById('salesSku').innerHTML=list.map(item=>`<option value="${escapeNo10Html(item.id)}">${escapeNo10Html(item.name)} ${escapeNo10Html(item.variant)} · ${escapeNo10Html(item.id)}</option>`).join('')||'<option value="">対象SKUなし</option>'}
function refreshEventSkus(){const store=document.getElementById('eventStore').value,category=document.getElementById('eventCategory').value,select=document.getElementById('eventSku'),previous=select.value,list=skuData.filter(item=>(store==='all'||item.store===store)&&(category==='all'||item.category===category));select.innerHTML='<option value="">指定なし</option>'+list.map(item=>`<option value="${escapeNo10Html(item.id)}">${escapeNo10Html(item.name)} ${escapeNo10Html(item.variant)} · ${escapeNo10Html(item.id)}</option>`).join('');if(list.some(item=>item.id===previous))select.value=previous}
function renderRows(){const rows=document.getElementById('skuRows');rows.innerHTML=skuData.map(item=>`<tr><td>${escapeNo10Html(storeInfo[item.store]?.name||item.store)}</td><td><strong>${escapeNo10Html(item.name)} ${escapeNo10Html(item.variant)}</strong><span class="sku-meta">${escapeNo10Html(item.category)} · ${escapeNo10Html(item.id)}</span></td><td>${Number(item.start)||0}点</td><td>${Number(item.current)||0}点</td><td>${item.salesLog?.length?`${Number(item.salesLog[item.salesLog.length-1].units)||0}点`:'—'}</td><td><div class="row-actions"><button type="button" data-edit-sku="${escapeNo10Html(item.id)}">修正</button><button type="button" class="danger" data-delete-sku="${escapeNo10Html(item.id)}">削除</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">SKUがありません。</td></tr>';rows.querySelectorAll('[data-edit-sku]').forEach(button=>button.addEventListener('click',()=>editSku(button.dataset.editSku)));rows.querySelectorAll('[data-delete-sku]').forEach(button=>button.addEventListener('click',()=>deleteSku(button.dataset.deleteSku)))}
function renderEvents(){const list=document.getElementById('eventRows');if(!eventData.length){list.innerHTML='<p class="empty">イベント予定はまだありません。</p>';return}list.innerHTML=eventData.slice().sort((a,b)=>a.startDate.localeCompare(b.startDate)).map(event=>{const scope=[event.store==='all'?'全店舗':storeInfo[event.store]?.name||event.store,event.category==='all'?'全カテゴリ':event.category,event.skuId||''].filter(Boolean).join(' · ');return `<div class="event-row"><div><strong>${escapeNo10Html(event.name)}</strong><small>${escapeNo10Html(event.startDate)}〜${escapeNo10Html(event.endDate)} · ${escapeNo10Html(scope)} · ${Number(event.discountPct)}%OFF / 販売数+${Number(event.upliftPct)}%想定</small></div><div class="event-actions"><button type="button" data-edit-event="${escapeNo10Html(event.id)}">修正</button><button type="button" class="danger" data-delete-event="${escapeNo10Html(event.id)}">削除</button></div></div>`}).join('');list.querySelectorAll('[data-edit-event]').forEach(button=>button.addEventListener('click',()=>editEvent(button.dataset.editEvent)));list.querySelectorAll('[data-delete-event]').forEach(button=>button.addEventListener('click',()=>deleteEvent(button.dataset.deleteEvent)))}
async function saveState(){await databaseRequest('inventory_forecast_state?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:1,payload:{skus:skuData,events:eventData},updated_at:new Date().toISOString()})})}
async function initialize(){document.querySelectorAll('.primary').forEach(button=>button.disabled=true);try{const rows=await databaseRequest('inventory_forecast_state?select=id,payload&id=eq.1');if(rows?.length){const saved=rows[0].payload;if(Array.isArray(saved)){skuData=saved;eventData=clone(demoEvents)}else if(saved&&Array.isArray(saved.skus)){skuData=saved.skus;eventData=Array.isArray(saved.events)?saved.events:clone(demoEvents)}else throw new Error('保存データの形式が不正です');status('Supabase接続済み')}else{eventData=clone(demoEvents);await saveState();status('サンプルデータをSupabaseに保存済み')}databaseReady=true}catch(error){console.warn('Supabase connection unavailable:',error);skuData=demoSkuData;eventData=clone(demoEvents);status('DB未接続・サンプル表示',true);['salesMessage','productMessage','salesCsvMessage','productCsvMessage','eventMessage'].forEach(id=>messageFor(id,'Supabaseに接続できないため登録・取込を停止しています。',true))}document.querySelectorAll('.primary').forEach(button=>button.disabled=!databaseReady);refreshSelectors();renderRows();renderEvents()}

const salesHeaders=['店舗コード','SKUコード','週次報告日','販売本数'];
const salesPreviewHeaders=[...salesHeaders,'現在庫（取込前）','現在庫（取込後）'];
const productHeaders=['店舗コード','カテゴリ','SKUコード','商品名','色・サイズ','販売開始時の在庫数','現在庫数'];
function csvCell(value){const text=String(value??'');return /[",\r\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text}
function downloadCsv(filename,headers){const blob=new Blob(['\uFEFF'+headers.map(csvCell).join(',')+'\r\n'],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++}else if(ch==='"')quoted=false;else cell+=ch}else if(ch==='"'){if(cell.length)throw new Error('CSVの引用符の位置が正しくありません。');quoted=true}else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'||ch==='\r'){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(value=>value.trim()))rows.push(row);row=[];cell=''}else cell+=ch}if(quoted)throw new Error('CSVの引用符が閉じられていません。');row.push(cell);if(row.some(value=>value.trim()))rows.push(row);return rows}
async function readCsv(input,required){const file=input.files?.[0];if(!file)throw new Error('CSVファイルを選んでください。');const rows=parseCsv((await file.text()).replace(/^\uFEFF/,''));if(rows.length<2)throw new Error('見出しとデータ行があるCSVを選んでください。');const headers=rows[0].map(value=>value.trim()),missing=required.filter(header=>!headers.includes(header));if(missing.length)throw new Error(`必要な列がありません：${missing.join('、')}`);return rows.slice(1).map((values,index)=>{if(values.length!==headers.length)throw new Error(`${index+2}行目の列数が見出しと一致しません。`);return Object.fromEntries(headers.map((header,i)=>[header,(values[i]??'').trim()]))})}
function countValue(value,label,row,{minimum=0}={}){if(!/^\d+$/.test(value))throw new Error(`${row}行目の「${label}」は0以上の整数で入力してください。`);const number=Number(value);if(!Number.isSafeInteger(number)||number<minimum)throw new Error(`${row}行目の「${label}」が有効な範囲ではありません。`);return number}
function validIsoDate(value,row,label){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error(`${row}行目の「${label}」はYYYY-MM-DD形式で入力してください。`);const date=new Date(`${value}T00:00:00Z`);if(Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==value)throw new Error(`${row}行目の「${label}」が正しくありません。`);return value}
function showPreview(kind,items,keys){const box=document.getElementById(kind==='sales'?'salesPreview':'productPreview'),normalized=kind==='sales'?items.map(item=>({'店舗コード':item.store,'SKUコード':item.id,'週次報告日':item.date,'販売本数':item.units,'現在庫（取込前）':item.beforeStock,'現在庫（取込後）':item.afterStock})):items.map(item=>({'店舗コード':item.store,'カテゴリ':item.category,'SKUコード':item.id,'商品名':item.name,'色・サイズ':item.variant,'販売開始時の在庫数':item.start,'現在庫数':item.current})),rows=normalized.slice(0,5).map(item=>`<tr>${keys.map(key=>`<td>${escapeNo10Html(item[key])}</td>`).join('')}</tr>`).join('');box.innerHTML=`<strong>${items.length}行を読み込みました。先頭${Math.min(items.length,5)}行の確認：</strong><table><thead><tr>${keys.map(key=>`<th>${escapeNo10Html(key)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table><div class="preview-actions">問題なければ、ボタンをもう一度押して反映します。</div>`;box.classList.add('visible')}
function clearPreview(kind,resetInput=false){pendingCsv[kind]=null;const box=document.getElementById(kind==='sales'?'salesPreview':'productPreview');box.classList.remove('visible');box.textContent='';const button=document.getElementById(kind==='sales'?'importSales':'importProducts');button.textContent=button.dataset.label;if(resetInput)document.getElementById(kind==='sales'?'salesCsv':'productCsv').value=''}
function setImportButton(button,busy){button.disabled=busy||!databaseReady;button.textContent=busy?'確認・保存中…':pendingCsv[button.id==='importSales'?'sales':'products']?'この内容で取り込む':button.dataset.label}
async function stageSalesCsv(){const rows=await readCsv(document.getElementById('salesCsv'),salesHeaders),items=rows.map((row,index)=>{const line=index+2,store=row['店舗コード'],id=row['SKUコード'],date=validIsoDate(row['週次報告日'],line,'週次報告日'),units=countValue(row['販売本数'],'販売本数',line);if(!storeInfo[store])throw new Error(`${line}行目の店舗コードはA〜Dで指定してください。`);const item=skuData.find(value=>value.store===store&&value.id===id);if(!item)throw new Error(`${line}行目のSKU「${id}」は${storeInfo[store].name}に登録されていません。`);return {store,id,date,units,item}}),seen=new Set(),deltaByItem=new Map();for(const entry of items){const key=`${entry.store}|${entry.id}|${entry.date}`;if(seen.has(key))throw new Error(`${entry.store}・${entry.id}・${entry.date}の行がCSV内で重複しています。`);seen.add(key);const old=(entry.item.salesLog||[]).find(log=>log.date===entry.date),delta=entry.units-(old?.units||0);deltaByItem.set(entry.item,(deltaByItem.get(entry.item)||0)+delta)}for(const [item,delta] of deltaByItem)if(item.current-delta<0)throw new Error(`${item.name}の在庫がマイナスになる販売数です。`);for(const entry of items){entry.beforeStock=entry.item.current;entry.afterStock=entry.item.current-deltaByItem.get(entry.item)}return items}
async function stageProductCsv(){const rows=await readCsv(document.getElementById('productCsv'),productHeaders),existing=new Set(skuData.map(item=>item.id)),seen=new Set();return rows.map((row,index)=>{const line=index+2,store=row['店舗コード'],category=row['カテゴリ'],id=row['SKUコード'],name=row['商品名'],variant=row['色・サイズ'],start=countValue(row['販売開始時の在庫数'],'販売開始時の在庫数',line,{minimum:1}),current=countValue(row['現在庫数'],'現在庫数',line);if(!storeInfo[store])throw new Error(`${line}行目の店舗コードはA〜Dで指定してください。`);if(!['アウター','トップス','ボトムス'].includes(category))throw new Error(`${line}行目のカテゴリが選択肢にありません。`);if(!id||!name||!variant)throw new Error(`${line}行目のSKUコード・商品名・色サイズを入力してください。`);if(existing.has(id)||seen.has(id))throw new Error(`${line}行目のSKUコード「${id}」は重複しています。`);if(current>start)throw new Error(`${line}行目の現在庫は販売開始時の在庫を超えています。`);seen.add(id);return {store,category,id,name,variant,start,current}})}
async function commitSales(items){const before=clone(skuData);try{for(const {item,date,units} of items){const logs=item.salesLog||(item.salesLog=[]),existing=logs.find(log=>log.date===date),delta=units-(existing?.units||0);item.current-=delta;if(existing)existing.units=units;else logs.push({date,units});logs.sort((a,b)=>a.date.localeCompare(b.date));item.history=logs.slice(-4).map(log=>log.units);if(item.start>0)item.curve[4]=Math.round((item.start-item.current)/item.start*1000)/10}await saveState()}catch(error){skuData=before;throw new Error('保存に失敗しました。内容は反映していません。Supabase接続を確認してください。')}messageFor('salesCsvMessage',`${items.length}行を反映しました。販売実績・現在庫を更新しました。`);clearPreview('sales',true);renderRows()}
async function commitProducts(items){const before=skuData;try{skuData=[...skuData,...items.map(item=>({...item,history:[],salesLog:[],markdown:0,markdownDate:null,sellout:null,endStock:item.current,reason:'販売実績不足のため未算出です。',curve:Array(16).fill(0)}))];await saveState()}catch(error){skuData=before;throw new Error('保存に失敗しました。登録内容は反映していません。Supabase接続を確認してください。')}messageFor('productCsvMessage',`${items.length}件のSKUを登録しました。`);clearPreview('products',true);refreshSelectors();renderRows()}
function setupCsvImport(kind){const button=document.getElementById(kind==='sales'?'importSales':'importProducts'),input=document.getElementById(kind==='sales'?'salesCsv':'productCsv'),messageId=kind==='sales'?'salesCsvMessage':'productCsvMessage',keys=kind==='sales'?salesPreviewHeaders:productHeaders;button.dataset.label=button.textContent;button.addEventListener('click',async()=>{if(!databaseReady)return;setImportButton(button,true);try{if(pendingCsv[kind]){await (kind==='sales'?commitSales(pendingCsv[kind]):commitProducts(pendingCsv[kind]))}else{const items=await (kind==='sales'?stageSalesCsv():stageProductCsv());pendingCsv[kind]=items;showPreview(kind,items,keys);button.textContent='この内容で取り込む';messageFor(messageId,'取込前の確認です。表示内容を確認してください。')}}catch(error){clearPreview(kind);button.textContent=button.dataset.label;messageFor(messageId,error.message||'CSVを処理できませんでした。',true)}finally{button.disabled=!databaseReady}});input.addEventListener('change',()=>{if(pendingCsv[kind])clearPreview(kind);messageFor(messageId,'CSVを選択しました。ボタンを押すと内容を確認できます。')})}

function resetProductForm(){document.getElementById('productForm').reset();document.getElementById('editSkuId').value='';document.getElementById('newId').readOnly=false;document.getElementById('newStart').value=50;document.getElementById('newCurrent').value=50;document.getElementById('productSubmit').textContent='SKUを登録';document.getElementById('cancelEdit').hidden=true;messageFor('productMessage','')}
function editSku(id){const item=skuData.find(value=>value.id===id);if(!item)return;document.getElementById('editSkuId').value=id;document.getElementById('newStore').value=item.store;document.getElementById('newCategory').value=item.category;document.getElementById('newId').value=item.id;document.getElementById('newId').readOnly=true;document.getElementById('newName').value=item.name;document.getElementById('newVariant').value=item.variant;document.getElementById('newStart').value=item.start;document.getElementById('newCurrent').value=item.current;document.getElementById('productSubmit').textContent='SKUを更新';document.getElementById('cancelEdit').hidden=false;document.getElementById('productForm').scrollIntoView({behavior:'smooth',block:'center'})}
async function deleteSku(id){const item=skuData.find(value=>value.id===id);if(!item||!databaseReady)return;if(!confirm(`${item.name}（${id}）を削除しますか？販売履歴も削除されます。`))return;const before=skuData,beforeEvents=eventData;skuData=skuData.filter(value=>value.id!==id);eventData=eventData.filter(event=>event.skuId!==id);try{await saveState();messageFor('productMessage',`${item.name}を削除しました。`);refreshSelectors();renderRows();renderEvents()}catch(error){skuData=before;eventData=beforeEvents;messageFor('productMessage','削除を保存できませんでした。',true)}}
document.getElementById('productForm').addEventListener('submit',async event=>{event.preventDefault();if(!databaseReady)return;const editId=document.getElementById('editSkuId').value,id=document.getElementById('newId').value.trim(),start=Number(document.getElementById('newStart').value),current=Number(document.getElementById('newCurrent').value);if(current>start){messageFor('productMessage','現在庫は販売開始時の在庫数以下にしてください。',true);return}const before=skuData,beforeEvents=eventData;if(!editId&&skuData.some(item=>item.id===id)){messageFor('productMessage','同じSKUコードがすでに登録されています。',true);return}const base={store:document.getElementById('newStore').value,category:document.getElementById('newCategory').value,id,name:document.getElementById('newName').value.trim(),variant:document.getElementById('newVariant').value.trim(),start,current};if(editId){skuData=skuData.map(item=>item.id===editId?{...item,...base}:item);eventData=eventData.map(item=>item.skuId===editId?{...item,store:base.store,category:base.category}:item)}else skuData=[...skuData,{...base,history:[],salesLog:[],markdown:0,markdownDate:null,sellout:null,endStock:current,reason:'販売実績不足のため未算出です。',curve:Array(16).fill(0)}];try{await saveState();messageFor('productMessage',editId?'SKU情報を更新しました。':'SKUを登録しました。');resetProductForm();refreshSelectors();renderRows();renderEvents()}catch(error){skuData=before;eventData=beforeEvents;messageFor('productMessage','保存できませんでした。入力内容は反映していません。',true)}});
document.getElementById('cancelEdit').addEventListener('click',resetProductForm);
document.getElementById('salesStore').addEventListener('change',refreshSalesSkus);
document.getElementById('eventStore').addEventListener('change',refreshEventSkus);
document.getElementById('eventCategory').addEventListener('change',refreshEventSkus);
document.getElementById('eventSku').addEventListener('change',event=>{const item=skuData.find(value=>value.id===event.target.value);if(item){document.getElementById('eventStore').value=item.store;document.getElementById('eventCategory').value=item.category;refreshEventSkus();document.getElementById('eventSku').value=item.id}});

let editingEventId='';
function resetEventForm(){document.getElementById('eventForm').reset();editingEventId='';document.getElementById('eventStore').value='all';document.getElementById('eventCategory').value='all';document.getElementById('eventStart').value='2026-10-15';document.getElementById('eventEnd').value='2026-10-18';document.getElementById('eventDiscount').value=20;document.getElementById('eventUplift').value=50;document.getElementById('eventSubmit').textContent='予定を登録';document.getElementById('cancelEventEdit').hidden=true;refreshEventSkus();messageFor('eventMessage','')}
function editEvent(id){const item=eventData.find(event=>event.id===id);if(!item)return;editingEventId=id;document.getElementById('eventName').value=item.name;document.getElementById('eventStore').value=item.store;document.getElementById('eventCategory').value=item.category;refreshEventSkus();document.getElementById('eventSku').value=item.skuId||'';document.getElementById('eventStart').value=item.startDate;document.getElementById('eventEnd').value=item.endDate;document.getElementById('eventDiscount').value=item.discountPct;document.getElementById('eventUplift').value=item.upliftPct;document.getElementById('eventSubmit').textContent='予定を更新';document.getElementById('cancelEventEdit').hidden=false;document.getElementById('eventForm').scrollIntoView({behavior:'smooth',block:'center'})}
async function deleteEvent(id){if(!databaseReady||!confirm('このイベント予定を削除しますか？'))return;const before=eventData;eventData=eventData.filter(event=>event.id!==id);try{await saveState();renderEvents();messageFor('eventMessage','イベント予定を削除しました。')}catch(error){eventData=before;messageFor('eventMessage','削除を保存できませんでした。',true)}}
document.getElementById('eventForm').addEventListener('submit',async event=>{event.preventDefault();if(!databaseReady)return;const name=document.getElementById('eventName').value.trim(),skuId=document.getElementById('eventSku').value,startDate=document.getElementById('eventStart').value,endDate=document.getElementById('eventEnd').value;if(startDate>endDate){messageFor('eventMessage','終了日は開始日以降にしてください。',true);return}const scopedSku=skuData.find(item=>item.id===skuId),row={id:editingEventId||`event-${Date.now()}`,name,startDate,endDate,store:scopedSku?scopedSku.store:document.getElementById('eventStore').value,category:scopedSku?scopedSku.category:document.getElementById('eventCategory').value,skuId:scopedSku?.id||'',discountPct:Number(document.getElementById('eventDiscount').value),upliftPct:Number(document.getElementById('eventUplift').value)},before=eventData;eventData=editingEventId?eventData.map(item=>item.id===editingEventId?row:item):[...eventData,row];try{await saveState();messageFor('eventMessage',editingEventId?'イベント予定を更新しました。':'イベント予定を登録しました。');resetEventForm();renderEvents()}catch(error){eventData=before;messageFor('eventMessage','保存できませんでした。入力内容は反映していません。',true)}});
document.getElementById('cancelEventEdit').addEventListener('click',resetEventForm);
document.getElementById('salesTemplate').addEventListener('click',event=>{event.preventDefault();downloadCsv('No10_週次販売数テンプレート.csv',salesHeaders)});
document.getElementById('productTemplate').addEventListener('click',event=>{event.preventDefault();downloadCsv('No10_新規SKUテンプレート.csv',productHeaders)});
document.querySelectorAll('.csv-import').forEach(button=>button.dataset.label=button.textContent);
setupCsvImport('sales');setupCsvImport('products');
document.getElementById('salesForm').addEventListener('submit',async event=>{event.preventDefault();const item=skuData.find(value=>value.id===document.getElementById('salesSku').value),date=document.getElementById('salesDate').value,units=Number(document.getElementById('salesUnits').value);if(!item||!databaseReady)return;const logs=item.salesLog||(item.salesLog=[]),existing=logs.find(log=>log.date===date),delta=units-(existing?.units||0);if(item.current-delta<0){messageFor('salesMessage','販売数が現在庫を超えています。',true);return}const before=clone(skuData);item.current-=delta;if(existing)existing.units=units;else logs.push({date,units});logs.sort((a,b)=>a.date.localeCompare(b.date));item.history=logs.slice(-4).map(log=>log.units);if(item.start>0)item.curve[4]=Math.round((item.start-item.current)/item.start*1000)/10;try{await saveState();messageFor('salesMessage',`${item.name}の在庫を${item.current}点に更新しました。`);renderRows()}catch(error){skuData=before;messageFor('salesMessage','保存できませんでした。接続設定を確認してください。',true)}});
initialize();
